#!/usr/bin/env python3
"""
Reviewer 3 added-value ablation for the TCGA-BRCA multimodal MB signature.

Purpose
-------
This script directly addresses Reviewer 1 / Comment 3:
"compare the final multimodal model with a clinical-only model, an omics-only
model, and a clinical-plus-omics model."

Default assumptions match the existing repository workflow:
- run from: 01_Causal_feature_extraction/MB/
- merged data: ../MERGE_continuous_outer/08_composite.csv
- final selected features: results_final/selected_features/08_composite_features.csv
- outcomes: OS and OS.time
- model: penalized Cox, penalizer=5.0
- CV: 5-fold, random_state=42

Outputs
-------
Creates MB/results_reviewer3_added_value/ with:
- reviewer3_ablation_results.csv
- reviewer3_ablation_fold_metrics.csv
- reviewer3_feature_sets.csv
- reviewer3_table_for_manuscript.csv
- reviewer3_table_for_manuscript.tex
- reviewer3_ablation_report.txt
- reviewer3_ablation_barplot.png

Run
---
cd /path/to/Thesis_v3/01_Causal_feature_extraction/MB
python reviewer3_added_value_ablation.py

If your data are elsewhere:
python reviewer3_added_value_ablation.py \
  --data-file ../MERGE_continuous_outer/08_composite.csv \
  --selected-features results_final/selected_features/08_composite_features.csv
"""

from __future__ import annotations

import argparse
import json
import sys
import time
import warnings
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd
from lifelines import CoxPHFitter
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler

warnings.filterwarnings("ignore")

CLINICAL_PREFIX = "CLIN_"
OMICS_PREFIXES = ("RNA_", "CNV_", "MUT_", "PROT_", "METH_", "MIRNA_")
ALL_MODALITY_PREFIXES = (CLINICAL_PREFIX,) + OMICS_PREFIXES


# -----------------------------------------------------------------------------
# Path helpers
# -----------------------------------------------------------------------------

def _unique_paths(paths: Iterable[Path]) -> List[Path]:
    seen = set()
    out = []
    for p in paths:
        try:
            rp = p.resolve()
        except Exception:
            rp = p
        if str(rp) not in seen:
            out.append(p)
            seen.add(str(rp))
    return out


def infer_project_dir() -> Path:
    """Infer the 01_Causal_feature_extraction directory from script/cwd."""
    try:
        here = Path(__file__).resolve().parent
    except NameError:
        here = Path.cwd().resolve()

    candidates = _unique_paths(
        [here, Path.cwd().resolve()]
        + list(here.parents)
        + list(Path.cwd().resolve().parents)
    )

    for p in candidates:
        if p.name == "01_Causal_feature_extraction" and (p / "MB").exists():
            return p
        if (p / "01_Causal_feature_extraction" / "MB").exists():
            return p / "01_Causal_feature_extraction"
        if (p / "MB").exists() and (
            (p / "MERGE_continuous_outer").exists() or (p / "MERGE").exists()
        ):
            return p

    # Fallback: assume script is inside MB.
    if here.name == "MB":
        return here.parent
    return here


def find_dataset_file(project_dir: Path, dataset_name: str) -> Optional[Path]:
    """Find the merged CSV, defaulting to MERGE_continuous_outer/08_composite.csv."""
    filename = f"{dataset_name}.csv"
    candidates = [
        project_dir / "MERGE_continuous_outer" / filename,
        project_dir / "MERGE" / filename,
        project_dir / filename,
        project_dir / "MB" / "MERGE_continuous_outer" / filename,
        Path.cwd() / filename,
        Path.cwd() / "MERGE_continuous_outer" / filename,
    ]
    for p in candidates:
        if p.exists():
            return p.resolve()

    # Last-resort recursive search near the project only.
    search_roots = _unique_paths([project_dir, project_dir.parent, Path.cwd().resolve()])
    for root in search_roots:
        if not root.exists():
            continue
        matches = sorted(root.rglob(filename))
        matches = [m for m in matches if "selected_features" not in str(m)]
        if matches:
            return matches[0].resolve()
    return None


def find_selected_features_file(project_dir: Path, dataset_name: str) -> Optional[Path]:
    """Find selected feature CSV generated by final_mb_all_datasets_8.py."""
    candidates = [
        project_dir / "MB" / "results_final" / "selected_features" / f"{dataset_name}_features.csv",
        project_dir / "MB" / "results_final" / "selected_features" / f"{dataset_name}.csv",
        project_dir / "MB" / "results_final" / f"{dataset_name}_features.csv",
        project_dir / "MB" / "final_selected_features" / f"{dataset_name}_features.csv",
        Path.cwd() / "results_final" / "selected_features" / f"{dataset_name}_features.csv",
        Path.cwd() / "selected_features" / f"{dataset_name}_features.csv",
    ]
    for p in candidates:
        if p.exists():
            return p.resolve()

    search_roots = _unique_paths([project_dir / "MB", project_dir, Path.cwd().resolve()])
    patterns = [f"{dataset_name}_features.csv", f"{dataset_name}.csv"]
    for root in search_roots:
        if not root.exists():
            continue
        for pattern in patterns:
            matches = sorted(root.rglob(pattern))
            matches = [m for m in matches if "selected_features" in str(m) or "results_final" in str(m)]
            if matches:
                return matches[0].resolve()
    return None


# -----------------------------------------------------------------------------
# Data and feature helpers
# -----------------------------------------------------------------------------

def read_merged_dataset(path: Path, event_col: str, duration_col: str) -> pd.DataFrame:
    """Read CSV robustly. Existing code uses index_col=0, but we fallback if needed."""
    df = pd.read_csv(path, index_col=0)
    if event_col not in df.columns or duration_col not in df.columns:
        df = pd.read_csv(path)
    missing = [c for c in [event_col, duration_col] if c not in df.columns]
    if missing:
        raise ValueError(
            f"Outcome columns not found in {path}: {missing}. "
            f"Available columns start with: {list(df.columns[:20])}"
        )

    df = df.copy()
    df[event_col] = pd.to_numeric(df[event_col], errors="coerce")
    df[duration_col] = pd.to_numeric(df[duration_col], errors="coerce")
    df = df.dropna(subset=[event_col, duration_col])
    return df


def feature_columns(df: pd.DataFrame, event_col: str, duration_col: str) -> List[str]:
    excluded = {event_col, duration_col}
    return [c for c in df.columns if c not in excluded]


def read_selected_features(path: Path) -> List[str]:
    sel = pd.read_csv(path)
    if "feature" in sel.columns:
        feats = sel["feature"].astype(str).tolist()
    else:
        feats = sel.iloc[:, 0].astype(str).tolist()
    # Preserve order and remove duplicates.
    return list(dict.fromkeys([f for f in feats if f and f.lower() != "nan"]))


def is_clinical_feature(feature: str) -> bool:
    return feature.startswith(CLINICAL_PREFIX)


def is_omics_feature(feature: str) -> bool:
    return feature.startswith(OMICS_PREFIXES)


def modality_of(feature: str) -> str:
    for prefix in ALL_MODALITY_PREFIXES:
        if feature.startswith(prefix):
            return prefix.rstrip("_")
    return "OTHER"


def validate_features(df: pd.DataFrame, features: Sequence[str], label: str) -> List[str]:
    present = [f for f in features if f in df.columns]
    missing = [f for f in features if f not in df.columns]
    if missing:
        print(f"WARNING: {label}: {len(missing)} selected features were not found in the data.")
        for f in missing[:20]:
            print(f"  missing: {f}")
        if len(missing) > 20:
            print(f"  ... {len(missing) - 20} more missing features")
    if not present:
        raise ValueError(f"No usable features found for {label}.")
    return present


def coerce_numeric(df: pd.DataFrame, cols: Sequence[str]) -> pd.DataFrame:
    out = df.copy()
    for c in cols:
        out[c] = pd.to_numeric(out[c], errors="coerce")
    return out


# -----------------------------------------------------------------------------
# Feature selection fallback if selected feature file is absent
# -----------------------------------------------------------------------------

def cox_topn(
    df: pd.DataFrame,
    feat_cols: Sequence[str],
    n: int,
    event_col: str,
    duration_col: str,
    penalizer: float,
) -> List[str]:
    """Match the existing final script: univariate penalized Cox p-value ranking."""
    pvals: Dict[str, float] = {}
    for col in feat_cols:
        try:
            sub = df[[col, event_col, duration_col]].dropna().copy()
            if sub[col].nunique(dropna=True) <= 1 or len(sub) < 40 or sub[event_col].sum() < 3:
                pvals[col] = 1.0
                continue
            cph = CoxPHFitter(penalizer=penalizer)
            cph.fit(sub[[col, event_col, duration_col]], duration_col=duration_col, event_col=event_col)
            pvals[col] = float(cph.summary["p"].iloc[0])
        except Exception:
            pvals[col] = 1.0
    return sorted(pvals, key=lambda x: pvals[x])[:n]


# -----------------------------------------------------------------------------
# Metrics
# -----------------------------------------------------------------------------

def cindex_risk(times: np.ndarray, events: np.ndarray, scores: np.ndarray) -> float:
    """
    Manual C-index matching the existing repo logic:
    higher score = higher risk = shorter survival.
    """
    times = np.asarray(times, dtype=float)
    events = np.asarray(events, dtype=int)
    scores = np.asarray(scores, dtype=float)

    n_conc = 0
    n_disc = 0
    n_tied = 0

    for i in range(len(times)):
        for j in range(i + 1, len(times)):
            if events[i] == 0 and events[j] == 0:
                continue
            if times[i] == times[j]:
                continue
            early, late = (i, j) if times[i] < times[j] else (j, i)
            if events[early] == 0:
                continue
            if scores[early] > scores[late]:
                n_conc += 1
            elif scores[early] < scores[late]:
                n_disc += 1
            else:
                n_tied += 1

    total = n_conc + n_disc + n_tied
    return float((n_conc + 0.5 * n_tied) / total) if total > 0 else np.nan


def valid_5yr_rows(df: pd.DataFrame, event_col: str, duration_col: str, threshold_days: float) -> Tuple[np.ndarray, np.ndarray]:
    """
    Keep patients whose 5-year status is observable:
    - event at or before 5 years -> positive
    - event after 5 years or censored after 5 years -> negative
    - censored before 5 years -> excluded
    """
    t = df[duration_col].to_numpy(dtype=float)
    e = df[event_col].to_numpy(dtype=int)
    keep = (t >= threshold_days) | (e == 1)
    y = ((e == 1) & (t <= threshold_days)).astype(int)
    return keep, y


def auc5_from_risk(
    test: pd.DataFrame,
    risk_scores: np.ndarray,
    event_col: str,
    duration_col: str,
    threshold_days: float,
) -> float:
    keep, y = valid_5yr_rows(test, event_col, duration_col, threshold_days)
    if keep.sum() < 5:
        return np.nan
    y_keep = y[keep]
    if len(np.unique(y_keep)) < 2:
        return np.nan
    try:
        return float(roc_auc_score(y_keep, risk_scores[keep]))
    except Exception:
        return np.nan


def auc5_logistic_legacy(
    train: pd.DataFrame,
    test: pd.DataFrame,
    features: Sequence[str],
    event_col: str,
    duration_col: str,
    threshold_days: float,
    seed: int,
) -> float:
    """
    Legacy 5-year ROC-AUC matching final_mb_all_datasets_8.py:
    Logistic regression on 5-year event labels using the same feature set.
    """
    if not features:
        return np.nan
    keep_tr, ytr_all = valid_5yr_rows(train, event_col, duration_col, threshold_days)
    keep_te, yte_all = valid_5yr_rows(test, event_col, duration_col, threshold_days)

    s5tr = train.loc[keep_tr]
    s5te = test.loc[keep_te]
    ytr = ytr_all[keep_tr]
    yte = yte_all[keep_te]

    if len(s5tr) < 20 or len(s5te) < 5:
        return np.nan
    if len(np.unique(ytr)) < 2 or len(np.unique(yte)) < 2:
        return np.nan

    try:
        scaler = StandardScaler()
        xtr = scaler.fit_transform(s5tr[list(features)])
        xte = scaler.transform(s5te[list(features)])
        lr = LogisticRegression(C=0.1, max_iter=500, random_state=seed)
        lr.fit(xtr, ytr)
        pred = lr.predict_proba(xte)[:, 1]
        return float(roc_auc_score(yte, pred))
    except Exception:
        return np.nan


def fallback_risk_score(train: pd.DataFrame, test: pd.DataFrame, features: Sequence[str]) -> np.ndarray:
    """Fallback if Cox fails: mean standardized feature score, same spirit as existing code."""
    if not features:
        return np.zeros(len(test), dtype=float)
    try:
        scaler = StandardScaler()
        xtr = scaler.fit_transform(train[list(features)])
        xte = scaler.transform(test[list(features)])
        return np.nanmean(xte, axis=1)
    except Exception:
        return np.zeros(len(test), dtype=float)


def evaluate_feature_set_cv(
    df_common: pd.DataFrame,
    features: Sequence[str],
    model_name: str,
    event_col: str,
    duration_col: str,
    penalizer: float,
    n_folds: int,
    seed: int,
    survival_years: float,
    scale_for_cox: bool = False,
) -> pd.DataFrame:
    """Evaluate one feature set using identical folds across all models."""
    features = list(dict.fromkeys(features))
    threshold_days = survival_years * 365.0

    if len(features) == 0:
        raise ValueError(f"{model_name}: empty feature set.")

    sub = df_common[[duration_col, event_col] + features].dropna().copy()
    if len(sub) < n_folds:
        raise ValueError(f"{model_name}: not enough complete cases for {n_folds}-fold CV.")

    kf = KFold(n_splits=n_folds, shuffle=True, random_state=seed)
    rows = []

    for fold, (tr_idx, te_idx) in enumerate(kf.split(sub), start=1):
        train = sub.iloc[tr_idx].copy()
        test = sub.iloc[te_idx].copy()

        # Remove constant features within each training fold.
        usable = [f for f in features if train[f].nunique(dropna=True) > 1]

        cox_status = "ok"
        if usable:
            try:
                cph_train = train[[duration_col, event_col] + usable].copy()
                cph_test = test[[duration_col, event_col] + usable].copy()

                if scale_for_cox:
                    scaler = StandardScaler()
                    cph_train[usable] = scaler.fit_transform(cph_train[usable])
                    cph_test[usable] = scaler.transform(cph_test[usable])

                cph = CoxPHFitter(penalizer=penalizer)
                cph.fit(cph_train, duration_col=duration_col, event_col=event_col)
                risk = cph.predict_partial_hazard(cph_test).to_numpy().reshape(-1)
            except Exception as exc:
                cox_status = f"fallback: {type(exc).__name__}"
                risk = fallback_risk_score(train, test, usable)
        else:
            cox_status = "fallback: no usable features"
            risk = np.zeros(len(test), dtype=float)

        c_idx = cindex_risk(test[duration_col].values, test[event_col].values, risk)
        auc5_legacy = auc5_logistic_legacy(
            train=train,
            test=test,
            features=usable,
            event_col=event_col,
            duration_col=duration_col,
            threshold_days=threshold_days,
            seed=seed,
        )
        auc5_cox = auc5_from_risk(
            test=test,
            risk_scores=risk,
            event_col=event_col,
            duration_col=duration_col,
            threshold_days=threshold_days,
        )

        rows.append(
            {
                "model": model_name,
                "fold": fold,
                "n_train": len(train),
                "n_test": len(test),
                "n_train_events": int(train[event_col].sum()),
                "n_test_events": int(test[event_col].sum()),
                "n_features_requested": len(features),
                "n_features_used": len(usable),
                "c_index": c_idx,
                "auc_5yr": auc5_legacy,
                "auc_5yr_cox_risk": auc5_cox,
                "cox_status": cox_status,
            }
        )

    return pd.DataFrame(rows)


def summarize_fold_metrics(fold_df: pd.DataFrame, feature_sets: Dict[str, List[str]], clinical_reference: str) -> pd.DataFrame:
    rows = []
    for model, g in fold_df.groupby("model", sort=False):
        feats = feature_sets[model]
        rows.append(
            {
                "model": model,
                "n_features": len(feats),
                "n_clinical": sum(is_clinical_feature(f) for f in feats),
                "n_omics": sum(is_omics_feature(f) for f in feats),
                "n_other": sum((not is_clinical_feature(f)) and (not is_omics_feature(f)) for f in feats),
                "n_samples_common_complete_cases": int(g["n_train"].iloc[0] + g["n_test"].iloc[0]),
                "mean_train_events": float(g["n_train_events"].mean()),
                "mean_test_events": float(g["n_test_events"].mean()),
                "c_index_mean": float(np.nanmean(g["c_index"])),
                "c_index_sd": float(np.nanstd(g["c_index"], ddof=1)),
                "auc_5yr_mean": float(np.nanmean(g["auc_5yr"])),
                "auc_5yr_sd": float(np.nanstd(g["auc_5yr"], ddof=1)),
                "auc_5yr_cox_risk_mean": float(np.nanmean(g["auc_5yr_cox_risk"])),
                "auc_5yr_cox_risk_sd": float(np.nanstd(g["auc_5yr_cox_risk"], ddof=1)),
            }
        )

    summary = pd.DataFrame(rows)
    ref_row = summary.loc[summary["model"] == clinical_reference]
    if len(ref_row) == 1:
        ref_c = float(ref_row["c_index_mean"].iloc[0])
        ref_auc = float(ref_row["auc_5yr_mean"].iloc[0])
        summary["delta_c_index_vs_clinical"] = summary["c_index_mean"] - ref_c
        summary["delta_auc_5yr_vs_clinical"] = summary["auc_5yr_mean"] - ref_auc
    else:
        summary["delta_c_index_vs_clinical"] = np.nan
        summary["delta_auc_5yr_vs_clinical"] = np.nan
    return summary


def save_feature_sets(feature_sets: Dict[str, List[str]], out_dir: Path) -> pd.DataFrame:
    rows = []
    for model, feats in feature_sets.items():
        for rank, f in enumerate(feats, start=1):
            rows.append(
                {
                    "model": model,
                    "rank_in_selected_signature": rank,
                    "feature": f,
                    "modality": modality_of(f),
                    "group": "clinical" if is_clinical_feature(f) else ("omics" if is_omics_feature(f) else "other"),
                }
            )
    feat_df = pd.DataFrame(rows)
    feat_df.to_csv(out_dir / "reviewer3_feature_sets.csv", index=False)
    return feat_df


def save_manuscript_tables(summary: pd.DataFrame, out_dir: Path) -> pd.DataFrame:
    table = summary.copy()
    table["C-index"] = table.apply(lambda r: f"{r['c_index_mean']:.3f} ± {r['c_index_sd']:.3f}", axis=1)
    table["5-year AUC"] = table.apply(lambda r: f"{r['auc_5yr_mean']:.3f} ± {r['auc_5yr_sd']:.3f}", axis=1)
    table["Δ C-index vs clinical"] = table["delta_c_index_vs_clinical"].map(lambda x: "reference" if abs(x) < 1e-12 else f"{x:+.3f}")
    table["Δ AUC vs clinical"] = table["delta_auc_5yr_vs_clinical"].map(lambda x: "reference" if abs(x) < 1e-12 else f"{x:+.3f}")

    manuscript = table[
        [
            "model",
            "n_features",
            "n_clinical",
            "n_omics",
            "C-index",
            "5-year AUC",
            "Δ C-index vs clinical",
            "Δ AUC vs clinical",
        ]
    ].rename(
        columns={
            "model": "Model",
            "n_features": "No. features",
            "n_clinical": "Clinical features",
            "n_omics": "Omics features",
        }
    )
    manuscript.to_csv(out_dir / "reviewer3_table_for_manuscript.csv", index=False)
    try:
        manuscript.to_latex(out_dir / "reviewer3_table_for_manuscript.tex", index=False, escape=False)
    except Exception as exc:
        print(f"WARNING: could not write LaTeX table: {exc}")
    return manuscript


def save_plot(summary: pd.DataFrame, out_dir: Path) -> None:
    try:
        import matplotlib.pyplot as plt

        plot_df = summary.copy()
        x = np.arange(len(plot_df))
        width = 0.35

        fig, ax = plt.subplots(figsize=(9, 5))
        ax.bar(x - width / 2, plot_df["c_index_mean"], width, label="C-index")
        ax.bar(x + width / 2, plot_df["auc_5yr_mean"], width, label="5-year AUC")
        ax.set_xticks(x)
        ax.set_xticklabels(plot_df["model"], rotation=20, ha="right")
        ax.set_ylim(0.0, 1.0)
        ax.set_ylabel("Performance")
        ax.set_title("Added value of omics features beyond clinical variables")
        ax.legend()
        fig.tight_layout()
        fig.savefig(out_dir / "reviewer3_ablation_barplot.png", dpi=300)
        plt.close(fig)
    except Exception as exc:
        print(f"WARNING: could not save plot: {exc}")


def write_report(
    out_dir: Path,
    args: argparse.Namespace,
    project_dir: Path,
    data_file: Path,
    selected_features_file: Optional[Path],
    summary: pd.DataFrame,
    manuscript_table: pd.DataFrame,
    feature_sets: Dict[str, List[str]],
    n_total: int,
    n_common: int,
    n_events_common: int,
) -> None:
    combined_label = "Clinical + omics final signature"
    clinical_label = "Clinical-only final-signature subset"

    combined = summary.loc[summary["model"] == combined_label]
    clinical = summary.loc[summary["model"] == clinical_label]

    if len(combined) and len(clinical):
        delta_c = float(combined["delta_c_index_vs_clinical"].iloc[0])
        delta_auc = float(combined["delta_auc_5yr_vs_clinical"].iloc[0])
        if delta_c > 0.01 or delta_auc > 0.01:
            interpretation = "molecular features provided modest/measurable incremental prognostic value beyond clinical variables"
        elif delta_c >= -0.005 and delta_auc >= -0.005:
            interpretation = "molecular features did not substantially change discrimination but provided biological/regulatory context"
        else:
            interpretation = "clinical variables dominated; molecular features did not improve discrimination in this ablation"
    else:
        delta_c = np.nan
        delta_auc = np.nan
        interpretation = "interpret after reviewing the table"

    lines = []
    lines.append("REVIEWER 3 ADDED-VALUE ABLATION ANALYSIS")
    lines.append("=" * 78)
    lines.append(f"Project dir: {project_dir}")
    lines.append(f"Data file: {data_file}")
    lines.append(f"Selected features file: {selected_features_file if selected_features_file else 'NOT FOUND; regenerated with Cox top-N'}")
    lines.append(f"Output dir: {out_dir}")
    lines.append("")
    lines.append("SETTINGS")
    lines.append("-" * 78)
    lines.append(f"Dataset name: {args.dataset_name}")
    lines.append(f"Event column: {args.event_col}")
    lines.append(f"Duration column: {args.duration_col}")
    lines.append(f"Cox penalizer: {args.penalizer}")
    lines.append(f"CV folds: {args.n_folds}")
    lines.append(f"Random seed: {args.seed}")
    lines.append(f"Survival horizon: {args.survival_years} years")
    lines.append(f"Scale features for Cox: {args.scale_for_cox}")
    lines.append("")
    lines.append("COHORT")
    lines.append("-" * 78)
    lines.append(f"Rows after OS/OS.time filtering: {n_total}")
    lines.append(f"Common complete cases for all final-signature features: {n_common}")
    lines.append(f"Observed events in common set: {n_events_common}")
    lines.append("")
    lines.append("FEATURE SETS")
    lines.append("-" * 78)
    for model, feats in feature_sets.items():
        lines.append(f"{model}: {len(feats)} features")
        lines.append("  " + ", ".join(feats))
    lines.append("")
    lines.append("SUMMARY RESULTS")
    lines.append("-" * 78)
    display_cols = [
        "model",
        "n_features",
        "n_clinical",
        "n_omics",
        "c_index_mean",
        "c_index_sd",
        "auc_5yr_mean",
        "auc_5yr_sd",
        "delta_c_index_vs_clinical",
        "delta_auc_5yr_vs_clinical",
    ]
    lines.append(summary[display_cols].to_string(index=False, float_format=lambda x: f"{x:.4f}"))
    lines.append("")
    lines.append("TABLE READY FOR MANUSCRIPT")
    lines.append("-" * 78)
    lines.append(manuscript_table.to_string(index=False))
    lines.append("")
    lines.append("INTERPRETATION TEMPLATE")
    lines.append("-" * 78)
    lines.append(
        "In this ablation, the clinical-plus-omics final signature changed the C-index by "
        f"{delta_c:+.3f} and the 5-year AUC by {delta_auc:+.3f} relative to the clinical-only subset. "
        f"This suggests that {interpretation}."
    )
    lines.append("")
    lines.append("FILES WRITTEN")
    lines.append("-" * 78)
    for p in sorted(out_dir.glob("reviewer3_*")):
        lines.append(str(p.name))

    report = "\n".join(lines)
    print("\n" + report)
    with open(out_dir / "reviewer3_ablation_report.txt", "w", encoding="utf-8") as f:
        f.write(report)


# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------

def parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Reviewer 3 clinical/omics added-value ablation.")
    parser.add_argument("--data-file", type=Path, default=None, help="Path to merged dataset CSV. Default: auto-detect 08_composite.csv.")
    parser.add_argument("--selected-features", type=Path, default=None, help="Path to final selected features CSV. Default: auto-detect results_final/selected_features/08_composite_features.csv.")
    parser.add_argument("--dataset-name", default="08_composite", help="Merged dataset short name. Default: 08_composite.")
    parser.add_argument("--event-col", default="OS", help="Event indicator column. Default: OS.")
    parser.add_argument("--duration-col", default="OS.time", help="Survival time column. Default: OS.time.")
    parser.add_argument("--out-dir", type=Path, default=None, help="Output directory. Default: MB/results_reviewer3_added_value.")
    parser.add_argument("--penalizer", type=float, default=5.0, help="CoxPH penalizer. Default: 5.0.")
    parser.add_argument("--top-n", type=int, default=20, help="If selected feature file is absent, regenerate top-N features. Default: 20.")
    parser.add_argument("--n-folds", type=int, default=5, help="Number of CV folds. Default: 5.")
    parser.add_argument("--seed", type=int, default=42, help="Random seed. Default: 42.")
    parser.add_argument("--survival-years", type=float, default=5.0, help="AUC horizon in years. Default: 5.")
    parser.add_argument("--scale-for-cox", action="store_true", help="Standardize features inside each training fold before Cox. Off by default to match existing repo code.")
    return parser.parse_args(argv)


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = parse_args(argv)
    t0 = time.time()

    project_dir = infer_project_dir()
    mb_dir = project_dir / "MB" if (project_dir / "MB").exists() else Path.cwd()

    data_file = args.data_file.resolve() if args.data_file else find_dataset_file(project_dir, args.dataset_name)
    if data_file is None or not data_file.exists():
        print("ERROR: Could not find merged dataset CSV.", file=sys.stderr)
        print("Expected something like:", file=sys.stderr)
        print(f"  {project_dir / 'MERGE_continuous_outer' / (args.dataset_name + '.csv')}", file=sys.stderr)
        print("Use --data-file /path/to/08_composite.csv", file=sys.stderr)
        return 2

    selected_features_file = args.selected_features.resolve() if args.selected_features else find_selected_features_file(project_dir, args.dataset_name)

    out_dir = args.out_dir.resolve() if args.out_dir else (mb_dir / "results_reviewer3_added_value").resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    print("=" * 78)
    print("Reviewer 3 ablation: clinical-only vs omics-only vs clinical+omics")
    print("=" * 78)
    print(f"Project dir: {project_dir}")
    print(f"Data file: {data_file}")
    print(f"Selected features file: {selected_features_file if selected_features_file else 'not found; will regenerate top-N'}")
    print(f"Output dir: {out_dir}")

    df = read_merged_dataset(data_file, event_col=args.event_col, duration_col=args.duration_col)
    n_total = len(df)
    feat_cols = feature_columns(df, args.event_col, args.duration_col)
    df = coerce_numeric(df, feat_cols + [args.event_col, args.duration_col])

    if selected_features_file and selected_features_file.exists():
        final_features = read_selected_features(selected_features_file)
        source = "selected feature file"
    else:
        print("WARNING: selected feature file not found. Regenerating final top-N features from the merged dataset.")
        final_features = cox_topn(
            df=df,
            feat_cols=feat_cols,
            n=args.top_n,
            event_col=args.event_col,
            duration_col=args.duration_col,
            penalizer=args.penalizer,
        )
        source = "regenerated Cox top-N"
        pd.DataFrame({"feature": final_features, "modality": [modality_of(f) for f in final_features]}).to_csv(
            out_dir / f"{args.dataset_name}_regenerated_top{args.top_n}_features.csv", index=False
        )

    final_features = validate_features(df, final_features, "final selected signature")
    clinical_features = [f for f in final_features if is_clinical_feature(f)]
    omics_features = [f for f in final_features if not is_clinical_feature(f)]

    if not clinical_features:
        raise ValueError("No clinical features detected in final signature. Expected CLIN_ prefix.")
    if not omics_features:
        raise ValueError("No omics features detected in final signature. Expected non-CLIN_ prefixes.")

    # Use the same complete-case patient set for all three models for a fair comparison.
    common_cols = [args.duration_col, args.event_col] + final_features
    df_common = df[common_cols].dropna().copy()
    n_common = len(df_common)
    n_events_common = int(df_common[args.event_col].sum())
    if n_common < 40 or n_events_common < args.n_folds:
        raise ValueError(
            f"Not enough common complete cases/events for CV: n={n_common}, events={n_events_common}."
        )

    feature_sets: Dict[str, List[str]] = {
        "Clinical-only final-signature subset": clinical_features,
        "Omics-only final-signature subset": omics_features,
        "Clinical + omics final signature": final_features,
    }

    print("\nFinal feature source:", source)
    print(f"Final signature: {len(final_features)} features")
    print(f"  Clinical: {len(clinical_features)}")
    print(f"  Omics/non-clinical: {len(omics_features)}")
    print(f"Common complete-case set: n={n_common}, events={n_events_common}")

    # Evaluate all models.
    fold_metrics = []
    for model_name, feats in feature_sets.items():
        print(f"\nRunning CV for: {model_name} ({len(feats)} features)")
        fm = evaluate_feature_set_cv(
            df_common=df_common,
            features=feats,
            model_name=model_name,
            event_col=args.event_col,
            duration_col=args.duration_col,
            penalizer=args.penalizer,
            n_folds=args.n_folds,
            seed=args.seed,
            survival_years=args.survival_years,
            scale_for_cox=args.scale_for_cox,
        )
        fold_metrics.append(fm)
        print(
            f"  C-index={np.nanmean(fm['c_index']):.4f} ± {np.nanstd(fm['c_index'], ddof=1):.4f}; "
            f"AUC-5yr={np.nanmean(fm['auc_5yr']):.4f} ± {np.nanstd(fm['auc_5yr'], ddof=1):.4f}"
        )

    fold_df = pd.concat(fold_metrics, ignore_index=True)
    summary = summarize_fold_metrics(
        fold_df=fold_df,
        feature_sets=feature_sets,
        clinical_reference="Clinical-only final-signature subset",
    )

    # Save outputs.
    fold_df.to_csv(out_dir / "reviewer3_ablation_fold_metrics.csv", index=False)
    summary.to_csv(out_dir / "reviewer3_ablation_results.csv", index=False)
    feat_df = save_feature_sets(feature_sets, out_dir)
    manuscript_table = save_manuscript_tables(summary, out_dir)
    save_plot(summary, out_dir)

    # Save run metadata.
    metadata = {
        "project_dir": str(project_dir),
        "data_file": str(data_file),
        "selected_features_file": str(selected_features_file) if selected_features_file else None,
        "feature_source": source,
        "out_dir": str(out_dir),
        "settings": vars(args),
        "n_total_after_outcome_filter": n_total,
        "n_common_complete_cases": n_common,
        "n_events_common": n_events_common,
    }
    with open(out_dir / "reviewer3_run_metadata.json", "w", encoding="utf-8") as f:
        json.dump(metadata, f, indent=2, default=str)

    write_report(
        out_dir=out_dir,
        args=args,
        project_dir=project_dir,
        data_file=data_file,
        selected_features_file=selected_features_file,
        summary=summary,
        manuscript_table=manuscript_table,
        feature_sets=feature_sets,
        n_total=n_total,
        n_common=n_common,
        n_events_common=n_events_common,
    )

    print(f"\nDone in {time.time() - t0:.1f}s")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
